// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "seq.h"

Seq::Seq() {
  { main_window = new Fl_Double_Window(369, 257);
    main_window->user_data((void*)(this));
    { main_scroll = new SeqScroll(8, 55, 350, 195);
      main_scroll->box(FL_NO_BOX);
      main_scroll->color(FL_BACKGROUND_COLOR);
      main_scroll->selection_color(FL_BACKGROUND_COLOR);
      main_scroll->labeltype(FL_NORMAL_LABEL);
      main_scroll->labelfont(0);
      main_scroll->labelsize(14);
      main_scroll->labelcolor(FL_FOREGROUND_COLOR);
      main_scroll->align(Fl_Align(FL_ALIGN_TOP));
      main_scroll->when(FL_WHEN_RELEASE);
      main_scroll->end();
    } // SeqScroll* main_scroll
    { tempo = new Fl_Dial(13, 10, 25, 25, "Tempo");
      tempo->minimum(60);
      tempo->maximum(300);
      tempo->step(10);
      tempo->value(160);
    } // Fl_Dial* tempo
    { play = new Fl_Button(50, 10, 35, 30, "Play");
    } // Fl_Button* play
    { stop = new Fl_Button(91, 10, 35, 30, "Stop");
    } // Fl_Button* stop
    { clear = new Fl_Button(130, 10, 40, 30, "Clear");
    } // Fl_Button* clear
    { random = new Fl_Button(175, 10, 60, 30, "Random");
    } // Fl_Button* random
    main_window->end();
  } // Fl_Double_Window* main_window
}
