// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef seq_h
#define seq_h
#include <FL/Fl.H>
#include "seq_extend.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Dial.H>
#include <FL/Fl_Button.H>

class Seq {
public:
  Seq();
  Fl_Double_Window *main_window;
  SeqScroll *main_scroll;
  Fl_Dial *tempo;
  Fl_Button *play;
  Fl_Button *stop;
  Fl_Button *clear;
  Fl_Button *random;
};
#endif
