// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "a2v_interface.h"

A2VInterface::A2VInterface() {
  { main_window = new Fl_Double_Window(278, 373, "A2V");
    main_window->user_data((void*)(this));
    { send_a2v = new Fl_Button(90, 5, 80, 25, "Send A2V");
    } // Fl_Button* send_a2v
    { tree_a2v = new Fl_Tree(10, 40, 165, 310);
    } // Fl_Tree* tree_a2v
    { load_a2v = new Fl_Button(10, 5, 70, 25, "Load A2V");
    } // Fl_Button* load_a2v
    main_window->end();
  } // Fl_Double_Window* main_window
}
