// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef a2v_interface_h
#define a2v_interface_h
#include <FL/Fl.H>
#include "a2v_interface_extend.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Slider.H>

class A2VInterface {
public:
  A2VInterface();
  Fl_Double_Window *main_window;
  Fl_Tree *tree_a2v;
  Fl_Button *load_a2v;
  Fl_Check_Button *active;
  Fl_Button *delete_action;
  Fl_Input_Choice *add_action_choice;
  Fl_Button *add_action;
  Fl_Button *randomize_a2v;
  Fl_Button *randomize_channel;
  Fl_Button *load_channel;
  Fl_Button *save_channel;
  Fl_Button *load_action;
  Fl_Button *save_action;
  Fl_Button *randomize_action;
  Fl_Button *save_a2v;
  Fl_Group *group_model_obj;
  Table4X4 *model_obj_init_values_model2world;
  Vec3 *model_obj_init_values_ambient;
  Vec3 *model_obj_init_values_diffuse;
  Table4X4 *model_obj_final_values_model2world;
  Vec3 *model_obj_final_values_ambient;
  Vec3 *model_obj_final_values_diffuse;
  Fl_Input_Choice *model_obj_init_values_transfo_choice;
  Fl_Float_Input *model_obj_init_values_transfo_value;
  Fl_Input_Choice *model_obj_final_values_transfo_choice;
  Fl_Float_Input *model_obj_final_values_transfo_value;
  Fl_Button *model_obj_init_values_transfo_ok;
  Fl_Button *model_obj_final_values_transfo_ok;
  Fl_Input_Choice *model_obj_ch_obj;
  Fl_Input_Choice *model_obj_ch_mat;
  TimeGraph *model_obj_alpha_graph;
  Fl_Button *model_obj_alpha_graph_ok;
  Fl_Value_Slider *model_obj_init_values_shininess;
  Fl_Value_Slider *model_obj_final_values_shininess;
  Fl_Group *group_light;
  Vec3 *light_init_values_color;
  Vec4 *light_init_values_position_world;
  Vec3 *light_init_values_spot_cone_direction_world;
  Vec3 *light_final_values_color;
  Vec4 *light_final_values_position_world;
  Vec3 *light_final_values_spot_cone_direction_world;
  Fl_Group *group_vmat;
  Table4X4 *vmat_init_values_mat;
  Table4X4 *vmat_final_values_mat;
  Fl_Input_Choice *vmat_init_values_transfo_choice;
  Fl_Float_Input *vmat_init_values_transfo_value;
  Fl_Button *vmat_init_values_transfo_ok;
  Fl_Input_Choice *vmat_final_values_transfo_choice;
  Fl_Float_Input *vmat_final_values_transfo_value;
  Fl_Button *vmat_final_values_transfo_ok;
  TimeGraph *vmat_alpha_graph;
  Fl_Button *vmat_alpha_graph_ok;
  Fl_Button *defaultize_action;
  Fl_Button *defaultize_channel;
  Fl_Button *defaultize_a2v;
  Fl_Button *copy_init2final;
  TimeGraph *morph_graph;
  Fl_Button *morph_graph_ok;
  Fl_Input_Choice *enable_all_choice;
  Fl_Button *enable_all;
  Fl_Button *disable_all;
  Fl_Check_Button *retrig;
  Fl_Value_Slider *lifetime;
};
#endif
